name = "backend"
compatibility_date = "2024-10-01"
compatibility_flags = [ "nodejs_compat" ]

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTU1Y2FhOWEtZTNhZC00MTVhLWEyYmItZjA2NDE1NjgwOTIzIiwidGVuYW50X2lkIjoiNTkzMjVjZWIyYzYzOGM4MTc3Njc4OWYzZDk1MDM2MGFkZjU1NmVjYWE2NjdhNWM4OGM5ZTkzN2E1YzgxN2IwZSIsImludGVybmFsX3NlY3JldCI6IjNiMjVmYzk4LWRmNzEtNDZkYy04MzYyLWRiMGJjMmY1ZjQ5NCJ9.SnPaeSSQk-laaH_Y5Tc_GNRABjpovr1AE7oO7v5UY3A"
JWT_SECRET="aasddda"

